version: "3.8"

services:
  # Service untuk PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - astro-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Service untuk aplikasi Astro
  app:
    build: .
    container_name: astro-app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "4321:4321"
    depends_on:
      - db
    volumes:
      - .:/src
    networks:
      - astro-network

networks:
  astro-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
